### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by zenati** [bithavoc/multilang-hstore#11]
Is this project still alive?

Thanks.

**Comment by bithavoc** [comment]
Honestly I'm not doing too much ruby lately. I see some PR's open but I haven't had the time to check them out, is there anything you need?

**Comment by ghost** [comment]
Yes I'm wondering how to handle fallbacks in multilang.

With 2 locales `:fr` and `:en`, I have:

```
multilang :name, :content, required: 1
```

If I fill in the `:fr` and not `:en`, and if `I18n.locale => :en`, it should be able to fallback to `:fr`. Right now it returns nil.

Is this already made possible by the gem?

Is it also possible to translate the error to handle I18n?

```
record.errors[:attribute] << (options[:message] || t('multilang.not_filled'))
```

instead of

```
record.errors[:attribute] << "has..."
```

Can I make a pull request to update to use `t('')` ?
Thanks.

**Comment by ghost** [comment]
@bithavoc Any news? Thank you

**Comment by bithavoc** [comment]
Sorry I missed this notification, no it's not possible. We accept PR's :)
